module.export = {
  // This array of globs will match our token source files
  source: ['token/token-input.json'],
  format: {
    autoGeneratedFileHeader: () => {
        return ['Do not edit directly, this file was suto-generated']
    },
  },
  platforms: {
    // Create a json platform which uses our custom format
    // and exports it to a file /figma-tokens.json
    css: {
      transformGroup: 'css',
      buildPath: '/',
      files: [
        {
          destination: 'styleguide.css',
          format: 'css/variables',
          options: {
            fileHeader: 'autoGeneratedFileHeader',
          }
        },
      ],
    },
  },
};